name: ci

on:
  pull_request:
    branches:
      - main
	types:
	  - opened
	  - edited
	  - closed
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
